### ISSUE TITLE
Win32 changes broke the emulator

### ISSUE THREAD

**Issue by code-bythepound** [linappleii/linapple#145]
Something in the last checkin ae9fd934 (to remove win32 types) seems to have broken the emulator - the emulation will just crash to monitor on startup.  If I revert that checkin, it works.  I tried to look through the change but it is many files and many edits.  I couldn't find the issue.

![image](https://user-images.githubusercontent.com/45739283/89704587-41838b00-d912-11ea-90eb-028d43668653.png)

**Comment by ThorstenBr** [comment]
To be honest, I don't think that commit was a good. It was fine to replace types like BOOL with bool. But replacing "BYTE" with "unsigned char", "UINT16" and "WORD" with "unsigned short int" and "UINT32" with "unsigned int" made things only worse.

It didn't help with readability. And what's worse: there is no guarantee that "short int" is always a 16bit type for example - that depends on the compiler/platform. "long" is 64bit on x64, but 32bit on 32-bit systems for example. That's the reason why one uses types like "UINT32" in the first place - because they can easily mapped to matching base types, depending on the current compiler/platform.

If types needed to be replaced at all, they should have been replaced with other standard types provided by C++. I.e. standard "uint8" instead of "BYTE", "uint32" instead of "UINT32", "uint16" instead of "WORD" etc. That would have avoided the Windows-specific types, while still preserving readability and independence of the compiler/platform specs.

**Comment by code-bythepound** [comment]
I agree with everything you said.  Where should we go from here?

**Comment by maxolasersquad** [comment]
As the author of that commit I feel I should try to resolve the issues, though any help with identifying the problem and solution is appreciated. Before I submitted it I played Conan for a few levels without issue. I'll try to get to looking into it some time this week.

**Comment by code-bythepound** [comment]
I would suggest you start with a clean checkout and try running from the build directory without installing.  Something like  bin/linapple --conf etc/linapple/linapple.conf --d1 share/linapple/Master.dsk -b (in case a config file or something else on your system is fixing the issue).  That command line will crash (as above) unless the change is reverted.  Also, when in the crashed monitor the emulated display isn't rendered correctly.  Lines seem to overlap and other lines aren't rendered at all.
As far as where to look, i'm not sure.  I looked through many of the diffs and couldn't find a real problem.  Perhaps since you are more familiar with the emulator you may know where to start looking given the way it crashes to the monitor.

**Comment by ThorstenBr** [comment]
The emulator is no longer working due to the type changes of the flag variables in CPU.cpp.
All flags (flagc, flagn, flagv,flagz, etc) were of type BYTE before, holding a value matching the appropriate bit position of the original flag bits in the 6502's processor status register. The type changes converted them to "bool", so now they can only hold values 0 or 1 - not the appropriate bit value, required to emulate the flag from the 6502 processor register. Reverting all flag variables/parameters to BYTE in CPU.cpp restores emulator operation.

Still, I would humbly ask you to revert commit 6aa645aad1537ca7167fe2d2e9cd360b7846683e and replace this with a something much smaller, just replacing data types were it really makes sense. When processor registers are declared as BYTE, address variables as WORD etc, than this is much more readable - than using types like "unsigned char", "unsigned short int" etc. Also, the latter types are not even correct, since the bit width of int/short int/... is platform-specific (C/C++ only guarantees that the bit width of char <= short int <= int <= long int <= long long int). The previous types like BYTE, WORD, ... could always be mapped to a matching basic type.

Also, before the change it was really easy to merge new features from AppleWin. The Debugger sources I had ported were almost identical to AppleWin's sources before - with only few changes in certain areas, as required for the Linux port. After the change, I'm unable to compare or sync any new debugger features from AppleWin, since the sources now contain loads of diffs, so any merge results in tons on conflicts. And, I don't see any gain, that replacing those data types has actually brought the project. So, please reconsider whether this large change was really necessary... ;-)

**Comment by webspacecreations** [comment]
So glad to see I'm not the only one having problems. The codebase is currently broken and it sounds like a roll-back is in order.

**Comment by leesaudan2** [comment]
I'm also affected by this commit.  I've used 'git blame' to identify 6aa645aa as the source of the problem.

**Comment by 0cjs** [comment]
I'm also affected by this on Debian 9 and 11. (I didn't bother to check 10, but I can do that if necessary.) I originally put my notes [on the PR](https://github.com/linappleii/linapple/pull/123#issuecomment-897348484) , but I'll move them here since this seems to be the place to discuss it.
___________

This is very broken on Debian 9 and Debian 11 (and I am guessing most Linux systems). I tested commit 6aa645a to confirm that the issue wasn't with the subsequent merge commit. (BTW, this is why it's nice in the simple case to skip the merge commit and merely append the PR's commits to the head of the main branch.) Both cases below work fine on the previous commit, c93579f.

When I start with no disk I get the following:
![linapple-6aa645a-nodisk](https://user-images.githubusercontent.com/2586652/129139983-c511acf9-ea31-4904-b5ba-7e62b676a292.png)

With a bootable disk that has DOS 3.3 on it:
![linapple-6aa645a-dos33](https://user-images.githubusercontent.com/2586652/129140008-6c80e008-27cc-484e-80fb-0bcc0c2d9792.png)

**Comment by akhepcat** [comment]
`
git clone https://github.com/linappleii/linapple.git
cd linapple
make
build/bin/linapple --conf res/linapple.conf -b --d1 res/Master.dsk
echo "crashes to monitor"

git revert 6aa645a
make clean
make
build/bin/linapple --conf res/linapple.conf -b --d1 res/Master.dsk
echo "boots cleanly"

echo "Linux 5.11.0-31-generic #33-Ubuntu SMP Wed Aug 11 13:19:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux"
echo "Ubuntu 21.04"

`

Really, all of this should be converted to explicit-length datatypes  (uint8_t,  int32_t, etc..)  and that will solve most of these problems down the line of having unexpected variable sizes on different platforms.

**Comment by akhepcat** [comment]
Put my code where my mouth was:   https://github.com/linappleii/linapple/pull/169

It probably isn't pretty, but it's more than enough to get things working again on 32bit  and 64bit systems.

**Comment by akhepcat** [comment]
As 169 is now merged, this issue should now be solved.
