### ISSUE TITLE
Successfully running from source

### ISSUE THREAD

**Issue by webspacecreations** [linappleii/linapple#152]
Taking into account https://github.com/linappleii/linapple/issues/145, the following steps result in a working compilation of linapple as of November 2020:

1.) git clone --recursive https://github.com/linappleii/linapple.git linappleii
2.) cd linappleii
3.) git reset --hard HEAD^
4.) make
5.) cp build/bin/linapple linapple
6.) cp build/share/linapple/Master.dsk Master.dsk

You may quickly test that all is well by executing `./linapple -b` to auto-boot the Master disk. `./linapple -h` for help.

NOTICE: To verify that step 3 is necessary, do the following:
a.) git history
b.) verify the latest commit is ae9fd93457469c260ba53a20246ad1669df1ba6e made on June 1

**Comment by theflynn49** [comment]
I am running linapple on Kubuntu 18.04 (64 bits) ; for me c93579f works, but ae9fd93 is broken as per [https://github.com/linappleii/linapple/issues/145]

**Comment by webspacecreations** [comment]
Interesting. My instructions were tested on Raspbian (32 bits).

**Comment by theflynn49** [comment]
Honestly, there must be a misunderstanding somewhere, because I don't see how this could work with src/CPU.cpp messed up as it is ... [read this comment](https://github.com/linappleii/linapple/issues/145#issuecomment-699518529)  
That been said, it's tricky to know what is the exact impact of replacing 'BYTE' by 'bool' on different systems, may well be not portable...   Someone should clean up this mess, it took me 2 days wandering around to figure it out, since the ticket with the correct answer has been closed ...

**Comment by raz-ziv** [comment]
> I am running linapple on Kubuntu 18.04 (64 bits) ; for me [c93579f](https://github.com/linappleii/linapple/commit/c93579fc7e71d3bd339079338cd9b2f05916828c) works, but [ae9fd93](https://github.com/linappleii/linapple/commit/ae9fd93457469c260ba53a20246ad1669df1ba6e) is still broken as per [#145](https://github.com/linappleii/linapple/issues/145)

Same here - ubuntu 20.10

**Comment by bodhi-baum** [comment]
Here it just worked by doing make and make install under Linux Mint 20.1.

**Comment by leesaudan2** [comment]
As mentioned in https://github.com/linappleii/linapple/issues/145#issuecomment-671091456, the problem with #123 is that the changes break linapple on 64-bit platforms.

So, guys, when reporting whether it works on your system, please also give information on the architecture of your machine (not just OS version) using the `arch` command.  On my desktop, it breaks, and:
```
$ arch
x86_64
```

**Comment by bodhi-baum** [comment]
Well, here it runs smoothly at an 
$ arch
x86_64

**Comment by Nerun** [comment]
<code>arch x86_64</code> here

Tested:
* ae9fd93 - compile <code>ok</code> - install <code>ok</code> - run <code>ok</code> - disk load <code>not ok</code>
* 6aa645a - compile <code>ok</code> - install <code>ok</code> - run <code>ok</code> - disk load <code>not ok</code>
* c93579f - compile <code>ok</code> - install <code>ok</code> - run <code>ok</code> - disk load <code>ok</code>

By run understand: write <code>linapple</code> at terminal.

By disk load understand: <code>CTRL+F2</code>.

So i confirm the issue in 64 bits platforms for build 6aa645a and above. The problem is surely at 6aa645a. You should start looking there.
