### ISSUE TITLE
Core team

### ISSUE THREAD

**Issue by maxolasersquad** [linappleii/linapple#42]
Given the discussion in #8 I think we should see who is willing to come together for this project. I'm starting this issue to work that out.

**Comment by iKarith** [comment]
You, Chris, and Greg are all project owners, so you should be able to make whatever changes you feel are necessary. That wasn't necessary to do things like merge PRs, but you can decide who needs what level of access, add other members, etc. I don't know if @cpressey considers himself active enough often enough to want that responsibility, for example, but the three of you had what were essentially the major trees when I got started trying to pull everything together and so that's what I ran with. Definitely should be more than one person in case somebody gets run over by a rhinoceros or something.

**Comment by ghedger** [comment]
FWIW I'm in this for the long haul.  Sometimes responses may take awhile, but I'm committed to this project and have been since the AppleWin days w/Tom Charlesworth.
