### ISSUE TITLE
F2 vs Ctrl-F2 for reset

### ISSUE THREAD

**Issue by ThorstenBr** [linappleii/linapple#80]
Minor issue on the splash screen shown immediately after start-up. It says "Press F2 to reset".
F2 does not trigger a reset though - it's Ctrl-F2...

**Comment by ghedger** [comment]
Yes, needs to be changed.  F2 was problematic: you're playing a game (esp. a RPG that requires mutliple disk swaps) and you accidently hit "F2" instead of F3 and BOOM.  You just rebooted and all your progress is lost.

Thanks for the heads-up vis-a-vis the image discrepancy.

**Comment by ghedger** [comment]
Looks like it's a Grade A pain in the ass to change these images.  Seems like a simple fix, but because it's using XPM format, not so simple...  Wonder how tough it would be to just have it be something normal and modern like a JPG or PNG... Suspect this ties back to the ancient SDL 1.2 that we're currently one -- big project to go to SDL 2.*

**Comment by ghedger** [comment]
Splash screen is now ugly, but task completed.  I'm going to leave this issue open, however, for better minds to comment.

It seems the strength of XPM is that the images can be embedded directly into the linapple binary.  This, in contrast to JPG and PNG files which must be loaded extrenally, where we end right back up at the where-should-the-companion-files live problem that provided the impetus for the registry discussion.
